USE master;
-- CREATING THE DATABASE
CREATE DATABASE DataWareHouse;

USE DataWareHouse;
-- CREATING THE SCHEMAS FOR OUR LAYERS
CREATE SCHEMA bronze;
GO
CREATE SCHEMA silver;
GO
CREATE SCHEMA gold;
GO
